// Code generated by MockGen. DO NOT EDIT.
// Source: entropy.go

// Package mock_entropy is a generated GoMock package.
package mock_entropy

import (
	reflect "reflect"

	entropy "github.com/adroge/entropy"
	gomock "github.com/golang/mock/gomock"
)

// MockFunction is a mock of Function interface.
type MockFunction struct {
	ctrl     *gomock.Controller
	recorder *MockFunctionMockRecorder
}

// MockFunctionMockRecorder is the mock recorder for MockFunction.
type MockFunctionMockRecorder struct {
	mock *MockFunction
}

// NewMockFunction creates a new mock instance.
func NewMockFunction(ctrl *gomock.Controller) *MockFunction {
	mock := &MockFunction{ctrl: ctrl}
	mock.recorder = &MockFunctionMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFunction) EXPECT() *MockFunctionMockRecorder {
	return m.recorder
}

// Alphabets mocks base method.
func (m *MockFunction) Alphabets(newAlphabets []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Alphabets", newAlphabets)
	ret0, _ := ret[0].(error)
	return ret0
}

// Alphabets indicates an expected call of Alphabets.
func (mr *MockFunctionMockRecorder) Alphabets(newAlphabets interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Alphabets", reflect.TypeOf((*MockFunction)(nil).Alphabets), newAlphabets)
}

// Bounds mocks base method.
func (m *MockFunction) Bounds(veryWeak, weak, reasonable, strong float64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Bounds", veryWeak, weak, reasonable, strong)
	ret0, _ := ret[0].(error)
	return ret0
}

// Bounds indicates an expected call of Bounds.
func (mr *MockFunctionMockRecorder) Bounds(veryWeak, weak, reasonable, strong interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Bounds", reflect.TypeOf((*MockFunction)(nil).Bounds), veryWeak, weak, reasonable, strong)
}

// Calculate mocks base method.
func (m *MockFunction) Calculate(input string) (entropy.EntropyResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Calculate", input)
	ret0, _ := ret[0].(entropy.EntropyResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Calculate indicates an expected call of Calculate.
func (mr *MockFunctionMockRecorder) Calculate(input interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Calculate", reflect.TypeOf((*MockFunction)(nil).Calculate), input)
}

// Descriptions mocks base method.
func (m *MockFunction) Descriptions(tags entropy.DescriptionTags) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Descriptions", tags)
	ret0, _ := ret[0].(error)
	return ret0
}

// Descriptions indicates an expected call of Descriptions.
func (mr *MockFunctionMockRecorder) Descriptions(tags interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Descriptions", reflect.TypeOf((*MockFunction)(nil).Descriptions), tags)
}

// EntropyBounds mocks base method.
func (m *MockFunction) EntropyBounds() []float64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EntropyBounds")
	ret0, _ := ret[0].([]float64)
	return ret0
}

// EntropyBounds indicates an expected call of EntropyBounds.
func (mr *MockFunctionMockRecorder) EntropyBounds() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EntropyBounds", reflect.TypeOf((*MockFunction)(nil).EntropyBounds))
}
